### This YAML file sets environment variables for the application.
## Paths
resume_version: "./pdfs/juan_palmeros_resume.pdf"
profile_picture: "./images/profile_pic.png"
banorte_picture: "./images/banorte.jpg"
banxico_picture: "./images/banxico.jpg"
cide_picture: "./images/cide.jpeg"
itam_picture: "./images/itam.jpg"


## Directories
css_file: "./styles/main.css"

## Variables
email: "palmerosjuanfrancisco@gmail.com"

palette:
  dark_cyan: "#0d2c2f"
  cyan: "#01555f"
  red: "#ce505c"
  soft_red: "#f0839a"
  pale_pink: "#ffe4ed"