### This YAML file sets environment variables for the application.
## Paths
resume_version: "./pdfs/juan_palmeros_resume.pdf"
profile_picture: "./images/profile_pic.png"

## Directories
css_file: "./styles/main.css"