name: portfolio_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.3
  - pandas
  - numpy
  - matplotlib
  - jupyterlab
  - pip
  - scikit-learn
  - seaborn
  - streamlit
  - plotly
  - pyyaml


